"""Live Bedrock integration tests for Pipecat Flows.

Phase 0.3: Validates FlowManager + AWSBedrockLLMService with real Bedrock API calls.

Tests verify:
    - AWSBedrockLLMService processes inference through Pipecat's frame pipeline
    - Bedrock accepts tool schemas generated by FlowManager's UniversalLLMAdapter
    - RESET_WITH_SUMMARY generates a coherent summary via Bedrock
    - Direct functions produce valid Bedrock-compatible tool definitions

Requires: AWS credentials (voice-agent-deploy profile) with Bedrock access.

Run with:
    AWS_PROFILE=voice-agent-deploy pytest tests/test_flows_bedrock_live.py -v
"""

import json
import os

import boto3
import pytest

pytestmark = pytest.mark.integration

try:
    from pipecat.adapters.schemas.function_schema import FunctionSchema
    from pipecat.adapters.schemas.tools_schema import ToolsSchema
    from pipecat.processors.aggregators.llm_context import LLMContext

    from pipecat_flows import (
        ContextStrategy,
        ContextStrategyConfig,
        FlowResult,
        NodeConfig,
    )
    from pipecat_flows.types import FlowsDirectFunctionWrapper
except ImportError:
    pytest.skip(
        "Container-only dependencies not available (pipecat/pipecat-flows)",
        allow_module_level=True,
    )


# =============================================================================
# Configuration
# =============================================================================

AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")
# Use Haiku for speed and cost -- same model used in production
MODEL_ID = os.environ.get("LLM_MODEL_ID", "us.anthropic.claude-3-5-haiku-20241022-v1:0")


def get_bedrock_client():
    """Get a Bedrock runtime client, skip if credentials unavailable."""
    try:
        session = boto3.Session(region_name=AWS_REGION)
        client = session.client("bedrock-runtime")
        # Quick credential check
        client.meta.region_name
        return client
    except Exception as e:
        pytest.skip(f"AWS credentials not available: {e}")


# =============================================================================
# Direct function definitions (same as will be used in Phase 1)
# =============================================================================


async def transfer(flow_manager, target: str, reason: str) -> tuple[FlowResult, None]:
    """Transfer the caller to a different specialist or back to reception.

    Args:
        target: The specialist to transfer to. One of: computer_support,
                billing, appointment, reception.
        reason: Brief explanation of why the transfer is needed.
    """
    return {"transferred_to": target, "reason": reason}, None


async def search_knowledge_base(flow_manager, query: str) -> tuple[FlowResult, None]:
    """Search the knowledge base for troubleshooting guides and documentation.

    Args:
        query: Natural language search query describing the issue.
    """
    return {
        "found": True,
        "results": [{"content": "Try restarting your router."}],
    }, None


# =============================================================================
# Test: Direct functions produce valid Bedrock tool schemas
# =============================================================================


class TestDirectFunctionToolSchemas:
    """Verify that direct functions produce tool schemas Bedrock accepts."""

    def test_transfer_function_schema_is_valid(self):
        """Transfer function should produce a schema with target and reason params."""
        wrapper = FlowsDirectFunctionWrapper(function=transfer)
        schema = wrapper.to_function_schema()

        assert schema.name == "transfer"
        assert "target" in schema.properties
        assert "reason" in schema.properties
        assert schema.properties["target"]["type"] == "string"
        assert schema.properties["reason"]["type"] == "string"
        assert "target" in schema.required
        assert "reason" in schema.required

    def test_search_kb_function_schema_is_valid(self):
        """KB search function should produce a schema with query param."""
        wrapper = FlowsDirectFunctionWrapper(function=search_knowledge_base)
        schema = wrapper.to_function_schema()

        assert schema.name == "search_knowledge_base"
        assert "query" in schema.properties
        assert schema.properties["query"]["type"] == "string"

    def test_tools_schema_serializes_for_bedrock(self):
        """ToolsSchema containing direct functions should be serializable."""
        transfer_wrapper = FlowsDirectFunctionWrapper(function=transfer)
        kb_wrapper = FlowsDirectFunctionWrapper(function=search_knowledge_base)

        tools_schema = ToolsSchema(
            standard_tools=[
                transfer_wrapper.to_function_schema(),
                kb_wrapper.to_function_schema(),
            ]
        )

        # Verify ToolsSchema is not empty
        assert tools_schema is not None


# =============================================================================
# Test: Bedrock Converse API accepts FlowManager-style tool definitions
# =============================================================================


class TestBedrockAcceptsFlowsToolSchemas:
    """Verify that Bedrock's Converse API accepts the tool schemas
    generated by Flows' direct functions via UniversalLLMAdapter."""

    def _build_bedrock_tool_config(self, functions):
        """Convert direct functions to Bedrock toolConfig format.

        This replicates what happens inside the pipeline: FlowManager creates
        ToolsSchema -> Pipecat's Bedrock adapter converts to native format.
        """
        tools = []
        for func in functions:
            wrapper = FlowsDirectFunctionWrapper(function=func)
            schema = wrapper.to_function_schema()
            tool_spec = {
                "toolSpec": {
                    "name": schema.name,
                    "description": schema.description,
                    "inputSchema": {
                        "json": {
                            "type": "object",
                            "properties": schema.properties,
                            "required": schema.required,
                        }
                    },
                }
            }
            tools.append(tool_spec)
        return {"tools": tools}

    def test_bedrock_accepts_transfer_tool(self):
        """Bedrock should accept a Converse call with the transfer tool schema."""
        client = get_bedrock_client()
        tool_config = self._build_bedrock_tool_config([transfer])

        response = client.converse(
            modelId=MODEL_ID,
            messages=[
                {
                    "role": "user",
                    "content": [{"text": "My laptop won't connect to WiFi."}],
                }
            ],
            system=[
                {
                    "text": (
                        "You are a receptionist. Identify the caller's intent and "
                        "transfer them to the appropriate specialist using the "
                        "transfer function."
                    )
                }
            ],
            toolConfig=tool_config,
        )

        assert response["ResponseMetadata"]["HTTPStatusCode"] == 200
        # The model should either call transfer or provide text
        stop_reason = response["stopReason"]
        assert stop_reason in ("tool_use", "end_turn")

    def test_bedrock_calls_transfer_for_routing(self):
        """Bedrock should call the transfer tool when given a clear routing intent."""
        client = get_bedrock_client()
        tool_config = self._build_bedrock_tool_config([transfer])

        response = client.converse(
            modelId=MODEL_ID,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "text": "I need help with my WiFi connection. It keeps dropping."
                        }
                    ],
                }
            ],
            system=[
                {
                    "text": (
                        "You are a receptionist. Your ONLY job is to route callers "
                        "to specialists. When the caller describes a technical issue, "
                        "immediately use the transfer function with target='computer_support'. "
                        "Do NOT try to help them yourself."
                    )
                }
            ],
            toolConfig=tool_config,
        )

        assert response["stopReason"] == "tool_use"

        # Extract the tool use block
        output_message = response["output"]["message"]
        tool_uses = [
            block["toolUse"]
            for block in output_message["content"]
            if "toolUse" in block
        ]
        assert len(tool_uses) >= 1
        assert tool_uses[0]["name"] == "transfer"
        assert tool_uses[0]["input"]["target"] == "computer_support"

    def test_bedrock_accepts_specialist_tool_set(self):
        """Bedrock should accept a specialist's tool set (KB search + transfer)."""
        client = get_bedrock_client()
        tool_config = self._build_bedrock_tool_config([search_knowledge_base, transfer])

        response = client.converse(
            modelId=MODEL_ID,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"text": "My WiFi keeps disconnecting every 10 minutes."}
                    ],
                }
            ],
            system=[
                {
                    "text": (
                        "You are a computer support specialist. Help the caller "
                        "troubleshoot their issue. Use search_knowledge_base to "
                        "find relevant troubleshooting guides. Use transfer if "
                        "you need to route to another specialist."
                    )
                }
            ],
            toolConfig=tool_config,
        )

        assert response["ResponseMetadata"]["HTTPStatusCode"] == 200
        assert response["stopReason"] in ("tool_use", "end_turn")


# =============================================================================
# Test: RESET_WITH_SUMMARY generates coherent summaries
# =============================================================================


class TestResetWithSummarySummaryGeneration:
    """Verify that Bedrock generates coherent summaries for context resets."""

    def test_summary_generation_via_converse(self):
        """Bedrock should produce a coherent summary of a conversation."""
        client = get_bedrock_client()

        # Simulate the conversation history that RESET_WITH_SUMMARY would summarize
        conversation_history = [
            {
                "role": "user",
                "content": [{"text": "Hi, my laptop can't connect to WiFi."}],
            },
            {
                "role": "assistant",
                "content": [
                    {
                        "text": "I can help with that. Let me transfer you to our tech support team."
                    }
                ],
            },
        ]

        summary_prompt = (
            "Summarize the caller's technical issue and any details "
            "they provided. Be concise -- one or two sentences."
        )

        response = client.converse(
            modelId=MODEL_ID,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "text": f"Conversation history: {json.dumps(conversation_history)}\n\n{summary_prompt}"
                        }
                    ],
                }
            ],
            system=[{"text": summary_prompt}],
        )

        assert response["ResponseMetadata"]["HTTPStatusCode"] == 200
        assert response["stopReason"] == "end_turn"

        # Extract summary text
        output_content = response["output"]["message"]["content"]
        summary_text = "".join(
            block["text"] for block in output_content if "text" in block
        )

        assert len(summary_text) > 10
        # Summary should mention WiFi or laptop (the core issue)
        summary_lower = summary_text.lower()
        assert (
            "wifi" in summary_lower
            or "laptop" in summary_lower
            or "connect" in summary_lower
        )

    def test_summary_generation_with_multi_turn_history(self):
        """Bedrock should summarize a longer multi-turn conversation."""
        client = get_bedrock_client()

        conversation = [
            {
                "role": "user",
                "content": [
                    {"text": "I have a billing question about my last invoice."}
                ],
            },
            {
                "role": "assistant",
                "content": [
                    {
                        "text": "I'd be happy to help with billing. Can you tell me your account number?"
                    }
                ],
            },
            {
                "role": "user",
                "content": [
                    {"text": "It's 4532. I was charged twice for the same service."}
                ],
            },
            {
                "role": "assistant",
                "content": [
                    {
                        "text": "I see the duplicate charge. Let me look into that for you."
                    }
                ],
            },
        ]

        summary_prompt = (
            "Summarize the caller's billing concern, any account "
            "information already verified, and the current status. Be concise."
        )

        response = client.converse(
            modelId=MODEL_ID,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "text": f"Conversation history: {json.dumps(conversation)}\n\n{summary_prompt}"
                        }
                    ],
                }
            ],
            system=[{"text": summary_prompt}],
        )

        summary_text = "".join(
            block["text"]
            for block in response["output"]["message"]["content"]
            if "text" in block
        )

        summary_lower = summary_text.lower()
        # Should mention billing/charge/duplicate
        assert (
            "billing" in summary_lower
            or "charge" in summary_lower
            or "duplicate" in summary_lower
            or "invoice" in summary_lower
        )


# =============================================================================
# Test: Tool swap mid-conversation (simulating node transition)
# =============================================================================


class TestToolSwapMidConversation:
    """Verify that Bedrock handles tool set changes between turns,
    simulating what happens during a FlowManager node transition."""

    def _build_bedrock_tool_config(self, functions):
        """Build Bedrock toolConfig from direct functions."""
        tools = []
        for func in functions:
            wrapper = FlowsDirectFunctionWrapper(function=func)
            schema = wrapper.to_function_schema()
            tool_spec = {
                "toolSpec": {
                    "name": schema.name,
                    "description": schema.description,
                    "inputSchema": {
                        "json": {
                            "type": "object",
                            "properties": schema.properties,
                            "required": schema.required,
                        }
                    },
                }
            }
            tools.append(tool_spec)
        return {"tools": tools}

    def test_tool_set_changes_between_turns(self):
        """Bedrock should accept a different tool set on the second turn.

        This simulates: Turn 1 (reception) has transfer tool only.
        Turn 2 (specialist) has KB search + transfer tools.
        """
        client = get_bedrock_client()

        # Turn 1: Reception with transfer only
        reception_tools = self._build_bedrock_tool_config([transfer])

        response1 = client.converse(
            modelId=MODEL_ID,
            messages=[
                {
                    "role": "user",
                    "content": [{"text": "I need computer help."}],
                }
            ],
            system=[{"text": "You are a receptionist. Route the caller."}],
            toolConfig=reception_tools,
        )
        assert response1["ResponseMetadata"]["HTTPStatusCode"] == 200

        # Turn 2: Specialist with KB search + transfer (different tool set)
        specialist_tools = self._build_bedrock_tool_config(
            [search_knowledge_base, transfer]
        )

        response2 = client.converse(
            modelId=MODEL_ID,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"text": "My WiFi keeps dropping. Can you look up any guides?"}
                    ],
                }
            ],
            system=[
                {
                    "text": (
                        "You are a computer support specialist. "
                        "Use search_knowledge_base to find troubleshooting guides."
                    )
                }
            ],
            toolConfig=specialist_tools,
        )

        assert response2["ResponseMetadata"]["HTTPStatusCode"] == 200
        # The specialist should try to search the KB
        assert response2["stopReason"] in ("tool_use", "end_turn")
